/** Shared between DevToolsClient's per-user activity section and ActivityPanel's global feed. */
export const ACTIVITY_LABELS: Record<string, string> = {
  REGISTERED: "Registrations",
  LOGIN: "Logins",
  EMAIL_CHANGED: "Email changes",
  PHONE_CHANGED: "Phone changes",
  NAME_CHANGED: "Name changes",
  USERID_CHANGED: "Profile ID changes",
  ROLE_CHANGED: "Role changes",
  DOB_CHANGED: "Date of birth changes",
  GENDER_CHANGED: "Gender changes",
  PASSWORD_CHANGED: "Password changes",
  COUNTRY_CHANGED: "Country changes",
  STATE_CHANGED: "State changes",
  CITY_CHANGED: "City changes",
  SAVED_LOCATION_ADDED: "Saved locations added",
  SAVED_LOCATION_REMOVED: "Saved locations removed",
  REVIEW_SUBMITTED: "Reviews submitted",
  POST_CREATED: "Ads posted",
  POST_UPDATED: "Ads edited",
  POST_BUMPED: "Ads bumped",
  POST_DELETED: "Ads deleted",
  ALERT_CREATED: "Alerts created",
  ALERT_DELETED: "Alerts deleted",
  ALERT_STATUS_CHANGED: "Alerts paused/resumed",
  FAVOURITE_ADDED: "Favourites added",
  FAVOURITE_REMOVED: "Favourites removed",
  MESSAGE_SENT: "Messages sent",
  CONVERSATION_DELETED: "Conversations deleted",
  CONVERSATION_BLOCK_TOGGLED: "Conversation block changes",
  SESSION_REVOKED: "Devices signed out",
  ALL_SESSIONS_REVOKED: "“Sign out all other devices”",
  AD_REPORTED: "Ads reported",
  USER_HARD_DELETED: "Accounts permanently deleted",
  AD_APPROVED: "Ads approved",
  AD_REJECTED: "Ads rejected",
  AD_SET_PENDING: "Ads marked pending",
  AD_SUSPENDED: "Ads suspended",
  AD_RESTORED: "Ads restored",
  AD_REPORT_REVIEWED: "Reports reviewed",
  AD_REPORT_DISMISSED: "Reports dismissed",
};

/** Field name shown in the History revision table — only actions that carry {from, to} metadata need an entry. */
export const FIELD_NAMES: Record<string, string> = {
  EMAIL_CHANGED: "Email",
  PHONE_CHANGED: "Phone",
  NAME_CHANGED: "Full Name",
  USERID_CHANGED: "Profile ID",
  ROLE_CHANGED: "Role",
  DOB_CHANGED: "Date of Birth",
  GENDER_CHANGED: "Gender",
  COUNTRY_CHANGED: "Country",
  STATE_CHANGED: "State",
  CITY_CHANGED: "City",
  CONVERSATION_BLOCK_TOGGLED: "Blocked",
};
